env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:security/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - security
rules: {}
